using RGB.NET.Core;
using System.Collections.Generic;
using Vulcan.NET;

namespace RGB.NET.Devices.Vulcan
{
    public static class VulcanLedMapping
    {
        public static Dictionary<Key, LedId> Mapping { get; } = new()
        {
            [Key.ESC] = LedId.Keyboard_Escape,
            [Key.TILDE] = LedId.Keyboard_GraveAccentAndTilde,
            [Key.TAB] = LedId.Keyboard_Tab,
            [Key.CAPS_LOCK] = LedId.Keyboard_CapsLock,
            [Key.LEFT_SHIFT] = LedId.Keyboard_LeftShift,
            [Key.LEFT_CONTROL] = LedId.Keyboard_LeftCtrl,
            [Key.ONE] = LedId.Keyboard_1,
            [Key.Q] = LedId.Keyboard_Q,
            [Key.A] = LedId.Keyboard_A,
            [Key.ISO_BACKSLASH] = LedId.Keyboard_NonUsBackslash,
            [Key.LEFT_WINDOWS] = LedId.Keyboard_LeftGui,
            [Key.F1] = LedId.Keyboard_F1,
            [Key.TWO] = LedId.Keyboard_2,
            [Key.W] = LedId.Keyboard_W,
            [Key.S] = LedId.Keyboard_S,
            [Key.Z] = LedId.Keyboard_Z,
            [Key.LEFT_ALT] = LedId.Keyboard_LeftAlt,
            [Key.F2] = LedId.Keyboard_F2,
            [Key.THREE] = LedId.Keyboard_3,
            [Key.E] = LedId.Keyboard_E,
            [Key.D] = LedId.Keyboard_D,
            [Key.X] = LedId.Keyboard_X,
            [Key.F3] = LedId.Keyboard_F3,
            [Key.FOUR] = LedId.Keyboard_4,
            [Key.R] = LedId.Keyboard_R,
            [Key.F] = LedId.Keyboard_F,
            [Key.C] = LedId.Keyboard_C,
            [Key.F4] = LedId.Keyboard_F4,
            [Key.FIVE] = LedId.Keyboard_5,
            [Key.T] = LedId.Keyboard_T,
            [Key.G] = LedId.Keyboard_G,
            [Key.V] = LedId.Keyboard_V,
            [Key.SIX] = LedId.Keyboard_6,
            [Key.Y] = LedId.Keyboard_Y,
            [Key.H] = LedId.Keyboard_H,
            [Key.B] = LedId.Keyboard_B,
            [Key.SPACE] = LedId.Keyboard_Space,
            [Key.F5] = LedId.Keyboard_F5,
            [Key.SEVEN] = LedId.Keyboard_7,
            [Key.U] = LedId.Keyboard_U,
            [Key.J] = LedId.Keyboard_J,
            [Key.N] = LedId.Keyboard_N,
            [Key.F6] = LedId.Keyboard_F6,
            [Key.EIGHT] = LedId.Keyboard_8,
            [Key.I] = LedId.Keyboard_I,
            [Key.K] = LedId.Keyboard_K,
            [Key.M] = LedId.Keyboard_M,
            [Key.F7] = LedId.Keyboard_F7,
            [Key.NINE] = LedId.Keyboard_9,
            [Key.O] = LedId.Keyboard_O,
            [Key.L] = LedId.Keyboard_L,
            [Key.COMMA] = LedId.Keyboard_CommaAndLessThan,
            [Key.F8] = LedId.Keyboard_F8,
            [Key.ZERO] = LedId.Keyboard_0,
            [Key.P] = LedId.Keyboard_P,
            [Key.SEMICOLON] = LedId.Keyboard_SemicolonAndColon,
            [Key.PERIOD] = LedId.Keyboard_PeriodAndBiggerThan,
            [Key.RIGHT_ALT] = LedId.Keyboard_RightAlt,
            [Key.MINUS] = LedId.Keyboard_MinusAndUnderscore,
            [Key.OPEN_BRACKET] = LedId.Keyboard_BracketLeft,
            [Key.APOSTROPHE] = LedId.Keyboard_ApostropheAndDoubleQuote,
            [Key.FORWARD_SLASH] = LedId.Keyboard_SlashAndQuestionMark,
            [Key.FN_Key] = LedId.Keyboard_Function,
            [Key.F9] = LedId.Keyboard_F9,
            [Key.EQUALS] = LedId.Keyboard_EqualsAndPlus,
            [Key.CLOSE_BRACKET] = LedId.Keyboard_BracketRight,
            [Key.BACKSLASH] = LedId.Keyboard_Backslash,
            [Key.RIGHT_SHIFT] = LedId.Keyboard_RightShift,
            [Key.APPLICATION_SELECT] = LedId.Keyboard_Application,
            [Key.F10] = LedId.Keyboard_F10,
            [Key.F11] = LedId.Keyboard_F11,
            [Key.F12] = LedId.Keyboard_F12,
            [Key.BACKSPACE] = LedId.Keyboard_Backspace,
            [Key.ENTER] = LedId.Keyboard_Enter,
            [Key.RIGHT_CONTROL] = LedId.Keyboard_RightCtrl,
            [Key.ISO_HASH] = LedId.Keyboard_NonUsTilde,
            [Key.PRINT_SCREEN] = LedId.Keyboard_PrintScreen,
            [Key.INSERT] = LedId.Keyboard_Insert,
            [Key.DELETE] = LedId.Keyboard_Delete,
            [Key.ARROW_LEFT] = LedId.Keyboard_ArrowLeft,
            [Key.SCROLL_LOCK] = LedId.Keyboard_ScrollLock,
            [Key.HOME] = LedId.Keyboard_Home,
            [Key.END] = LedId.Keyboard_End,
            [Key.ARROW_UP] = LedId.Keyboard_ArrowUp,
            [Key.ARROW_DOWN] = LedId.Keyboard_ArrowDown,
            [Key.PAUSE_BREAK] = LedId.Keyboard_PauseBreak,
            [Key.PAGE_UP] = LedId.Keyboard_PageUp,
            [Key.PAGE_DOWN] = LedId.Keyboard_PageDown,
            [Key.ARROW_RIGHT] = LedId.Keyboard_ArrowRight,
            [Key.NUM_LOCK] = LedId.Keyboard_NumLock,
            [Key.NUM_SEVEN] = LedId.Keyboard_Num7,
            [Key.NUM_FOUR] = LedId.Keyboard_Num4,
            [Key.NUM_ONE] = LedId.Keyboard_Num1,
            [Key.NUM_ZERO] = LedId.Keyboard_Num0,
            [Key.NUM_SLASH] = LedId.Keyboard_NumSlash,
            [Key.NUM_EIGHT] = LedId.Keyboard_Num8,
            [Key.NUM_FIVE] = LedId.Keyboard_Num5,
            [Key.NUM_TWO] = LedId.Keyboard_Num2,
            [Key.NUM_ASTERISK] = LedId.Keyboard_NumAsterisk,
            [Key.NUM_NINE] = LedId.Keyboard_Num9,
            [Key.NUM_SIX] = LedId.Keyboard_Num6,
            [Key.NUM_THREE] = LedId.Keyboard_Num3,
            [Key.NUM_PERIOD] = LedId.Keyboard_NumPeriodAndDelete,
            [Key.NUM_MINUS] = LedId.Keyboard_NumMinus,
            [Key.NUM_PLUS] = LedId.Keyboard_NumPlus,
            [Key.NUM_ENTER] = LedId.Keyboard_NumEnter,
            [Key.MUTE] = LedId.Keyboard_MediaMute,
        };
    }
}
