name: Build Plugins

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone Plugins
        uses: actions/checkout@v4

      - name: Build Plugin
        run: dotnet publish -c Release src/Artemis.Plugins.Devices.RoccatVulcan.sln

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Artemis.Plugins.Devices.RoccatVulcan
          path: src/Artemis.Plugins.Devices.RoccatVulcan/bin/x64/Release/net8.0/publish
